### PR TITLE
Changes to support Jetty 12.0.0.beta3

### PR DESCRIPTION
**Pull request by joakime**
Introduce changes to support Jetty 12.0.0.beta3

### CODE REVIEW

**Comment by joakime** [comment]
@wilkinsona here's the PR showing the changes made to support Jetty 12.0.0.beta3

**Comment by wilkinsona** [comment]
Thanks, @joakime and @lorban. I've rolled these changes and a few others into my [`jetty-12` branch](https://github.com/wilkinsona/spring-boot/tree/jetty-12). Things appear to be making really good progress.

I've been looking at the JSP-related failures. I think they were (at least in part) caused by our `LoaderHidingResource`'s implementation of `iterator` not returning an iterator that just contains itself when the resource it's wrapping isn't a `CombinedResource`.

**Comment by lorban** [comment]
@wilkinsona Please let us know if you managed to make Spring boot compatible with Jetty 12's EE-10 support or if you encounter more problems.

Once that is done, we'd be interested to help you make Spring boot compatible with the Jetty 12 client, and maybe make Spring use the brand new Jetty 12 core API instead of using the servlets API where/if that makes sense.

Thank you for being part of the Jetty 12 early adopters!

**Comment by wilkinsona** [comment]
Thanks, @lorban. My [`jetty-12` branch](https://github.com/wilkinsona/spring-boot/tree/jetty-12) now builds cleanly. There may be some lurking problems but we're in good shape now to ship a Spring Boot 3.2 milestone with Jetty 12 support. As you've mentioned above, the last piece in the compatibility puzzle is support for Jetty 12's client. This will, in large part, be [handled in Spring Framework](https://github.com/spring-projects/spring-framework/issues/30698) as that's where the majority of the code is.

**Pull request closed without merging**
